name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/immortalwrt/immortalwrt.git
          git fetch upstream

      - name: Sync with upstream
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories
          git push origin master
